#if !canImport(ObjectiveC)
import XCTest

extension KeyValueStoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyValueStoreTests = [
        ("testNSUbiquitousKeyValueStoreConforms", testNSUbiquitousKeyValueStoreConforms),
        ("testUserDefaultsConforms", testUserDefaultsConforms),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(KeyValueStoreTests.__allTests__KeyValueStoreTests),
    ]
}
#endif
